services:
  - type: web
    name: sergak-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m sergak_bot.app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11